#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

ifeq (,$(filter $(CONFIG_LEDS_TRIGGER_TIMER),y m))
obj-m += ledtrig-timer.o
endif
obj-m += bp4f_ina238.o
obj-m += bp4f_isl68137.o
obj-m += bp4f_lm25066.o
obj-m += bp4f_ltc4286.o
obj-m += bp4f_max31790.o
obj-m += bp4f_mp2869.o
obj-m += bp4f_mp2891.o
obj-m += bp4f_mp2993.o
obj-m += bp4f_mp9941.o
obj-m += bp4f_tda38640.o
obj-m += bp4f_xdpe12284.o
obj-m += bp4f_xdpe152c4.o
obj-m += bp4f_adm1275.o
obj-m += bp4f_tmp401.o
obj-m += bp4f_tps25990.o
